### check server status
GET http://localhost:8000

# ====== Admin API
### post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName":"dhigtal",
    "lName":"Dhital",
    "email":"pep@yaf.com",
    "password":"123456",
    "phone":"0451644397",
    "address":"clearence",
    "dob":"1997/10/26"
}